### ISSUE TITLE
Footer troubles

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/gf_admin_page_popup#1]
У меня в firefox что-то некрасивое происходит внизу страницы. Я тебе атачу принтскрин.
![screenshot from 2016-11-22 23-17-13](https://cloud.githubusercontent.com/assets/17630965/20551817/0534c86e-b10a-11e6-825c-ac2ff78dddc7.png)

**Comment by Andrukas8** [comment]
все готово, наче получилось.
