### ISSUE TITLE
Минимальная ширина окна браузера

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/gf_admin_page_popup#2]
Твой попапчик сужается по мере того, как я уменьшаю ширину окна браузера. Потом в определенный момент он перестает сужается и появляется горизонтальный скролл в окне браузера. 

Это правильное поведение. Только есть одна проблема - попап сужается чрезмерно и последние где-то 100-200 пикселей внутри него форма "рассыпается" и теряет свою эстетическую красоту. Лучше зафиксировать минимальную ширину попапа как раз до того, как форма внутри него рассыпется.

Тоже атачу принтскрин.

![screenshot from 2016-11-22 23-20-19](https://cloud.githubusercontent.com/assets/17630965/20551858/8562a222-b10a-11e6-9949-f68f42dba344.png)

**Comment by Andrukas8** [comment]
Все готово - зафсиксировал. На всякий случай минимальную ширину элемента грида формы попапа тоже зафиксировал- так смотрится лучше если менять размер окна браузера при при зуме.
