### ISSUE TITLE
input[type=text] padding-right

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/gf_admin_page_popup#3]
Я згадав, що ми же українською спілкуємося))) Мені треба практикувати рідну мову.

Ще я все ж таки поймав тебе на недоліку. :) Ти чесно додав padding-left у тектові поля, щоб воні виглядали красиво (як на дизайні). Але ж треба також додати симетричний padding-right, щоб якщо юзер вписав забагато тексту (більше, ніж ширина текстового поля), то в нього з правого боку текстового поля також все має виглядати пристойно.

Ось принтскрін.

![screenshot from 2016-11-22 23-26-11](https://cloud.githubusercontent.com/assets/17630965/20551918/22b19b5a-b10b-11e6-936b-b4c2ecee5ba7.png)

**Comment by Andrukas8** [comment]
Слушна думка. Додав симетричний padding-right.
