### ISSUE TITLE
Приховати accessibility текст

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/gf_admin_page_popup#4]
Ще ти трохи невдало сховав текст на значку доллара. Він невидимий, бо ти йому дав color: transparent. Але якщо виділити текст. то він буде видимим, бо при виділенні переназначається колір (наприклад, можеш зробити ctrl + a, щоб виділти текст усієї сторінки). Тобі ще треба додати font-size: 0; і інколи я ще навіть дописую text-indent css правило.

![screenshot from 2016-11-22 23-29-08](https://cloud.githubusercontent.com/assets/17630965/20551969/8bdd791e-b10b-11e6-8b7c-8816ae1c0f8a.png)

**Comment by Andrukas8** [comment]
Готово, текст сховав. Дякую за підказку про переназначення кольора при виділенні.
