### ISSUE TITLE
Інпут, застилізований як текст

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/gf_admin_page_popup#5]
А навіщо ти зробив ось так:

<input name="carrier" id="carrier" value="Antillean" type="text">

? Ти зробив input але застилізував його під звичайний текст, я просто твоєї логіки не можу зрозуміти тут.

**Comment by Andrukas8** [comment]
не можу зрозуміти що ти маєш на увазі. Може текст не скопіювався або не вставився?

**Comment by Andrukas8** [comment]
Здається зрозумів про що їдеться - певне про Carriers. Так, я довго думав як правильніше зробити цей елемент, і вирівшив зробити саме як інпут але стилізований під текст - бо можливо це поле в майбутньому треба буде активувати, і якійсь інпут з нього додавати до пакету даних, що будуть відправлятися формою.

![carriers_input](https://cloud.githubusercontent.com/assets/21954163/20627206/32fcf900-b327-11e6-86b3-75555015910f.jpg)

**Comment by Andrukas8** [comment]
Готово, переробив. Тепер замість input там текст
HTML строка 314 - 315
CSS строка 522 - 531
