### ISSUE TITLE
Лєсєнка в коді

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/gf_admin_page_popup#6]
Вже майже нема проблем з відступами у твоєму коді, але ось що я зміг знайти:

```
                  <label class="checkbox-label">
                        <input type="checkbox" name="accStatus" id="accStatus" value="" checked> Active</label>
```
Тут вона зломана, бо <label> відкривається на одній "висоті", а закривається на іншій.

**Comment by Andrukas8** [comment]
Готово. Строки 256-258 файлу admin_page_popup.html
