### ISSUE TITLE
float vs display: block

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/gf_admin_page_popup#7]
Ти для .form-usd-icon вписав float: left; Але там краще буде display: block, бо усе, що ти хочеш, це зробити елемент блоковим, а не включити в ньому обтікання.

Справа в тому, що float автоматично вмикає тег у режим display: block, і тому ти його і використав, мабудь. Але візуально нічого не зміниться, якщо ти просто впишеш display: block (при тому, що в тебе буде на 1 "обтікаючий" елемент менше в коді).

**Comment by Andrukas8** [comment]
Готово. Строка 563 css файлу
