### ISSUE TITLE
Ахтунг! Радар визначив !important clause :)

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/gf_admin_page_popup#8]
!important можна використовувати коли ти бог, або коли ти поганий кодер. Всім смертним, упродовж життя можна його використовувати лише 10 разів за усе життя (потім після 10го використання життя автоматично закінчується). Ти вже використав 3 із 10. Краще побережи ті 7, що тобі залишились.

!important - це за рідким виключенням признак поганого коду. Почитай добре про пріоритети css селекторів, щоб краще розімути у якій пріоритетності вони будуть примінятись і таким чином врятувтись від !important.

В цьому конкретному випадку я би ввів якийсь ID на .form-wrapper.popup-wrapper тег, адже в тебе більше 1 відкритого попапа на сторінці не буде. І цей ID тобі дасть більше свободи у css для правильної пріоритетності.

**Comment by Andrukas8** [comment]
Готово. Виправив. Ввів id. Три "!important" відправлено на склад.
HTML строка 356
CSS строка 567
